#Copyright(c) 2014, Konrad Sobon
# @arch_laboratory, http://archi-lab.net 

import clr
import sys
RhinoIOPath = r'C:\Program Files\Dynamo 0.7'
if RhinoIOPath not in sys.path:
	sys.path.Add(RhinoIOPath)
clr.AddReference('ProtoGeometry')
clr.AddReferenceToFileAndPath(RhinoIOPath + r"\Rhino3dmIO.dll")
from Autodesk.DesignScript.Geometry import *
import Rhino as rc

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN
rhObjects = IN[0]

#check if object is a point
#if true convert to DS Point
dsPoints = []
for i in rhObjects:
	if type(i.Geometry) == rc.Geometry.Point:
		pointX = i.Geometry.Location.X
		pointY = i.Geometry.Location.Y
		pointZ = i.Geometry.Location.Z
		dsPoints.append(Point.ByCoordinates(pointX, pointY, pointZ))
	else:
		continue

#Assign your output to the OUT variable
OUT = dsPoints
